apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.openshift.io/inject-proxy: azure-file-csi-driver-operator
  labels:
    hypershift.openshift.io/managed-by: cluster-storage-operator
  name: azure-file-csi-driver-operator
  namespace: ${CONTROLPLANE_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: azure-file-csi-driver-operator
  strategy: {}
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: azure-file-csi-driver-operator
        hypershift.openshift.io/need-management-kas-access: "true"
        name: azure-file-csi-driver-operator
        openshift.storage.network-policy.all-egress: allow
        openshift.storage.network-policy.api-server: allow
        openshift.storage.network-policy.dns: allow
        openshift.storage.network-policy.operator-metrics-range: allow
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: hypershift.openshift.io/control-plane
                operator: In
                values:
                - "true"
            weight: 50
          - preference:
              matchExpressions:
              - key: hypershift.openshift.io/cluster
                operator: In
                values:
                - ${CONTROLPLANE_NAMESPACE}
            weight: 100
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  hypershift.openshift.io/hosted-control-plane: ${CONTROLPLANE_NAMESPACE}
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - start
        - -v=${LOG_LEVEL}
        - --guest-kubeconfig=/etc/guest-kubeconfig/kubeconfig
        env:
        - name: DRIVER_CONTROL_PLANE_IMAGE
          value: ${DRIVER_CONTROL_PLANE_IMAGE}
        - name: LIVENESS_PROBE_CONTROL_PLANE_IMAGE
          value: ${LIVENESS_PROBE_CONTROL_PLANE_IMAGE}
        - name: KUBE_RBAC_PROXY_CONTROL_PLANE_IMAGE
          value: ${KUBE_RBAC_PROXY_CONTROL_PLANE_IMAGE}
        - name: DRIVER_IMAGE
          value: ${DRIVER_IMAGE}
        - name: PROVISIONER_IMAGE
          value: ${PROVISIONER_IMAGE}
        - name: ATTACHER_IMAGE
          value: ${ATTACHER_IMAGE}
        - name: RESIZER_IMAGE
          value: ${RESIZER_IMAGE}
        - name: SNAPSHOTTER_IMAGE
          value: ${SNAPSHOTTER_IMAGE}
        - name: NODE_DRIVER_REGISTRAR_IMAGE
          value: ${NODE_DRIVER_REGISTRAR_IMAGE}
        - name: LIVENESS_PROBE_IMAGE
          value: ${LIVENESS_PROBE_IMAGE}
        - name: KUBE_RBAC_PROXY_IMAGE
          value: ${KUBE_RBAC_PROXY_IMAGE}
        - name: CLUSTER_CLOUD_CONTROLLER_MANAGER_OPERATOR_IMAGE
          value: ${CLUSTER_CLOUD_CONTROLLER_MANAGER_OPERATOR_IMAGE}
        - name: OPERATOR_IMAGE_VERSION
          value: ${OPERATOR_IMAGE_VERSION}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ${OPERATOR_IMAGE}
        imagePullPolicy: IfNotPresent
        name: azure-file-csi-driver-operator
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/guest-kubeconfig
          name: guest-kubeconfig
        - mountPath: /tmp
          name: tmp
      priorityClassName: hypershift-control-plane
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: azure-file-csi-driver-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - key: hypershift.openshift.io/control-plane
        operator: Exists
      - key: hypershift.openshift.io/cluster
        operator: Equal
        value: ${CONTROLPLANE_NAMESPACE}
      volumes:
      - name: guest-kubeconfig
        secret:
          secretName: service-network-admin-kubeconfig
      - emptyDir:
          medium: Memory
        name: tmp
