kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-storage-operator
  namespace: openshift-cluster-storage-operators
subjects:
- kind: ServiceAccount
  name: cluster-storage-operator
roleRef:
  kind: Role
  name: cluster-storage-operator
  apiGroup: rbac.authorization.k8s.io
