apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: storage
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
spec:
  managementState: Managed
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
