apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmware-vsphere-csi-driver-operator
  namespace: openshift-cluster-csi-drivers
  annotations:
    config.openshift.io/inject-proxy: vmware-vsphere-csi-driver-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vmware-vsphere-csi-driver-operator
  strategy: {}
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        name: vmware-vsphere-csi-driver-operator
    spec:
      containers:
      - args:
        - start
        - --listen=0.0.0.0:8445
        - -v=${LOG_LEVEL}
        - --terminate-on-files=/var/run/secrets/serving-cert/tls.crt
        - --terminate-on-files=/var/run/secrets/serving-cert/tls.key
        env:
        - name: DRIVER_IMAGE
          value: ${DRIVER_IMAGE}
        - name: PROVISIONER_IMAGE
          value: ${PROVISIONER_IMAGE}
        - name: ATTACHER_IMAGE
          value: ${ATTACHER_IMAGE}
        - name: RESIZER_IMAGE
          value: ${RESIZER_IMAGE}
        - name: SNAPSHOTTER_IMAGE
          value: ${SNAPSHOTTER_IMAGE}
        - name: NODE_DRIVER_REGISTRAR_IMAGE
          value: ${NODE_DRIVER_REGISTRAR_IMAGE}
        - name: LIVENESS_PROBE_IMAGE
          value: ${LIVENESS_PROBE_IMAGE}
        - name: VMWARE_VSPHERE_SYNCER_IMAGE
          value: ${VMWARE_VSPHERE_SYNCER_IMAGE}
        - name: KUBE_RBAC_PROXY_IMAGE
          value: ${KUBE_RBAC_PROXY_IMAGE}
        - name: OPERATOR_NAME
          value: vmware-vsphere-csi-driver-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ${OPERATOR_IMAGE}
        imagePullPolicy: IfNotPresent
        name: vmware-vsphere-csi-driver-operator
        resources:
          requests:
            memory: 50Mi
            cpu: 10m
        ports:
        - containerPort: 8445
          name: vsphere-omp
        volumeMounts:
        - name: trusted-ca-bundle
          mountPath: /etc/pki/ca-trust/extracted/pem
        - mountPath: /var/run/secrets/serving-cert
          name: vmware-vsphere-csi-driver-operator-metrics-serving-cert
        terminationMessagePolicy: FallbackToLogsOnError
      priorityClassName: system-cluster-critical
      serviceAccountName: vmware-vsphere-csi-driver-operator
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
      volumes:
      - name: trusted-ca-bundle
        configMap:
          name: vsphere-csi-driver-operator-trusted-ca-bundle
          items:
            - key: ca-bundle.crt
              path: tls-ca-bundle.pem
      - name: vmware-vsphere-csi-driver-operator-metrics-serving-cert
        secret:
          secretName: vmware-vsphere-csi-driver-operator-metrics-serving-cert
          optional: true
