apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsphere-problem-detector-operator
  namespace: openshift-cluster-storage-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vsphere-problem-detector-operator
  strategy: {}
  template:
    metadata:
      labels:
        name: vsphere-problem-detector-operator
    spec:
      containers:
      - args:
        - start
        - --listen=0.0.0.0:8444
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: ${OPERATOR_IMAGE}
        imagePullPolicy: IfNotPresent
        name: vsphere-problem-detector-operator
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
        ports:
        - containerPort: 8444
          name: vsphere-metrics
        volumeMounts:
        - mountPath: /var/run/secrets/serving-cert
          name: vsphere-problem-detector-serving-cert
      priorityClassName: system-cluster-critical
      serviceAccountName: vsphere-problem-detector-operator
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: "NoSchedule"
      volumes:
      - name: vsphere-problem-detector-serving-cert
        secret:
          secretName: vsphere-problem-detector-serving-cert
          optional: true
