apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-ebs-csi-driver-operator
spec:
  template:
    metadata:
      annotations:
        openshift.io/required-scc: restricted-v2
      labels:
        hypershift.openshift.io/need-management-kas-access: "true"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: hypershift.openshift.io/control-plane
                    operator: In
                    values:
                      - "true"
              weight: 50
            - preference:
                matchExpressions:
                  - key: hypershift.openshift.io/cluster
                    operator: In
                    values:
                      - ${CONTROLPLANE_NAMESPACE}
              weight: 100
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    hypershift.openshift.io/hosted-control-plane: ${CONTROLPLANE_NAMESPACE}
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
      - name: aws-ebs-csi-driver-operator
        env:
          - name: HYPERSHIFT_IMAGE
            value: ${HYPERSHIFT_IMAGE}
          - name: DRIVER_CONTROL_PLANE_IMAGE
            value: ${DRIVER_CONTROL_PLANE_IMAGE}
          - name: LIVENESS_PROBE_CONTROL_PLANE_IMAGE
            value: ${LIVENESS_PROBE_CONTROL_PLANE_IMAGE}
        volumeMounts:
          - mountPath: /etc/guest-kubeconfig
            name: guest-kubeconfig
          - mountPath: /var/run/secrets/openshift/serviceaccount
            name: web-identity-token
        terminationMessagePolicy: FallbackToLogsOnError
      priorityClassName: hypershift-control-plane
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: "NoSchedule"
        - key: hypershift.openshift.io/control-plane
          operator: Exists
        - key: hypershift.openshift.io/cluster
          operator: Equal
          value: ${CONTROLPLANE_NAMESPACE}
      volumes:
        - name: guest-kubeconfig
          secret:
            secretName: service-network-admin-kubeconfig
